### PR TITLE
[#36] Fix URL detection based on context

### LINKED ISSUE #36: Error when smartmedia is in course context
If you embed a video in a course context, e.g. the "summary" of a course section, the code gives errors such as:

`Exception - Call to a member function get_url() on bool`

This originates from here, wrongly assuming it is always in the course module context:

https://github.com/catalyst/moodle-filter_smartmedia/blob/63cc583928b332bd2b54b9f15449a12003632c6a/filter.php#L400-L407

### PR DESCRIPTION
**Pull request by matthewhilton**
Closes #36 

- Adds some better validation around course/module/system context.

# Testing
- Updated unit tests to test webservice urls in system,course and module context. I added these before fixing the issue, and was able to replicate the same error.

### Profile page:
Screenshot 2023-09-14 at 12-45-06 UNKN Admin User Public profile

### Inside course main summary
Screenshot 2023-09-14 at 12-44-30 UNKN Course Test course S

### Webservice in course context (format tiles, smartmedia inside section summary)
Screenshot 2023-09-14 at 12-44-23 UNKN Course Test course S

### Inside a module (mod_label)
image

### CODE REVIEW

File: filter.php [hunk 1]
```diff
@@ -501,6 +483,50 @@ private function replace($target, $fulltext) : array {
...
+
+        if ($context instanceof \context_course) {
+            $course = get_course($context->instanceid);
+        }
+
+        // If loaded via Ajax, guess the URL from the context.
+        if (strpos($url, 'lib/ajax/service.php') !== false) {
+
+            if ($context instanceof \context_module && !empty($course)) {
+                $url = new moodle_url('/course/view.php', ['id' => $course->id]);
```
Comment (Peterburnett) [inline filter.php:514]: I dont think this is quite right. Here we need to check if we were able to infer the $cm, and use its native URL if found.

Comment (Peterburnett) [reply filter.php:514]: We should only guess the URL in the context of a context_course

Comment (matthewhilton) [reply filter.php]: Ah you're right I wasn't sure what the URLs were being used for, now I understand they are for the switch optimised/source button.

I've changed up the logic a bit. Sometimes `$cm->get_url()` is null so it uses the course url and then if there is a cm url, it uses that instead.

Ive tested all kinds of scenarios e.g. course, course section, ajax course section, inside module and they are all working locally.
